// Generated by build.mjs from config.json, translations/ru.json and templates/*.md.
// Do not edit: change those files and run `mise run build`.
window.FLEX_CLAIMER_DATA = {
  "config": {
    "recipients": {
      "support": {
        "address": "flex-representative-support@amazon.com",
        "checked": true
      },
      "jeff": {
        "address": "jeff@amazon.com",
        "checked": false
      }
    },
    "issueTypes": [
      "late",
      "standing",
      "undelivered",
      "noAccess",
      "damaged",
      "oldIssues",
      "onTime",
      "minorLate",
      "payment",
      "overtime",
      "custom"
    ],
    "emailText": {
      "missingDate": "[block date]",
      "overnight": "ending the following day",
      "endingAt": "ending at",
      "stationLabel": "Station:",
      "detailsLabel": "Additional details:",
      "unknownStartTime": "Please do not ask me for the block start time, as I do not know it. The app shows only the date of the issue, not the time of the block in which it occurred. I cannot determine which specific block the issue occurred in. If I knew the block time, I would have included it.",
      "signoff": "Thank you,"
    }
  },
  "translations": {
    "ru": {
      "Flex Claimer — contact support": "Flex Claimer — письмо в поддержку",
      "A support email · in a few minutes": "Письмо в поддержку · за пару минут",
      "Language": "Язык",
      "Amazon Flex · driver assistant": "Amazon Flex · помощник водителя",
      "Tell us what happened.": "Расскажи, что случилось.",
      "Choose an issue and enter your block details. Get an email draft to review and open in your mail app.": "Выбери ситуацию и укажи блок. Шаблон станет письмом, которое можно проверить и открыть в почте.",
      "Issue and block": "Ситуация и блок",
      "Issue type": "Тип обращения",
      "Late Scan — unable to start a block": "Late Scan — не удалось начать блок",
      "Incorrect standing issue": "Ошибка в standing",
      "Undelivered packages — route exceeded the block": "Недоставленные — маршрут не уложился в блок",
      "Undelivered packages — no access after 8 PM": "Недоставленные — нет доступа после 20:00",
      "Damaged package — returned to the station": "Повреждённая посылка — возвращена на склад",
      "Undelivered packages — entries older than 2 months": "Недоставленные — записи старше 2 месяцев",
      "Delivered on time — incorrect late marks": "Доставлено вовремя — ошибочное опоздание",
      "Late delivery — no more than 5 minutes": "Опоздание до 5 минут",
      "Missing block payment": "Блок не оплачен",
      "Route exceeded the block time": "Маршрут занял больше времени",
      "Custom template": "Собственный шаблон",
      "Block date": "Дата блока",
      "Use the station’s local date and time.": "Дата и время по местному времени станции.",
      "Block start time": "Начало блока",
      "End time": "Конец",
      "· optional": "· необязательно",
      "Station": "Станция",
      "For example, DAX5": "Например, DAX5",
      "Name for signature": "Имя для подписи",
      "As shown in your Amazon Flex account": "Как в аккаунте Amazon Flex",
      "What happened": "Что произошло",
      "Details in English: arrival time, app error, contact with support…": "Уточнения на английском: время прибытия, ошибка, обращение в поддержку…",
      "These details will be added to the email without translation.": "Этот текст добавится в письмо без перевода.",
      "Edit template": "Изменить шаблон",
      "Edit the template for this issue type and save it in this browser.": "Шаблон выбранного типа можно изменить и сохранить в этом браузере.",
      "Template variables": "Переменные шаблона",
      "Subject template": "Шаблон темы",
      "Email template": "Шаблон письма",
      "{{block}} includes the date and time. An end time earlier than the start means the block ends the next day. Station details, additional information, and your signature are appended automatically if their variables are not in the template.": "{{block}} — дата и время целиком. Если конец раньше начала, блок заканчивается на следующий день. Данные станции, уточнения и подпись добавятся автоматически, если их переменных нет в шаблоне.",
      "Apply and save": "Применить и сохранить",
      "Restore default": "Вернуть исходный",
      "Your email": "Твоё письмо",
      "Template": "Шаблон",
      "Edited by you": "С твоими правками",
      "The block details have changed. Update the email to use them. This will replace your manual edits.": "Данные блока изменились. Обнови письмо, чтобы подставить их. Твои правки при этом будут заменены.",
      "Update from template": "Обновить из шаблона",
      "To": "Кому",
      "Both addresses": "Оба адреса",
      "Select the first address": "Выбрать первый адрес",
      "Select the second address": "Выбрать второй адрес",
      "First email address": "Первый email",
      "Second email address": "Второй email",
      "Other email address": "Другой email",
      "Select the other address": "Выбрать другой адрес",
      "Select recipients. Amazon addresses are fixed; you can add another email below.": "Отметь получателей. Адреса Amazon фиксированные; ниже можно добавить другой email.",
      "Subject": "Тема",
      "Email body": "Текст письма",
      "You can edit the subject and body. Check that every statement matches your situation.": "Тему и текст можно редактировать. Проверь, что все утверждения соответствуют твоей ситуации.",
      "Create email": "Создать email",
      "Copy text": "Копировать текст",
      "Your mail app will open with the recipients, subject, and body filled in. You send the email from there.": "Откроется почтовое приложение с получателем, темой и текстом. Отправку подтвердить нужно в нём.",
      "If your mail app does not open": "Если почта не открывается",
      "Set up your default mail app, or copy the text into a new email. Attach photos and other evidence in your mail app. Very long emails may not transfer in full — check the draft before sending.": "Настрой почтовое приложение по умолчанию или скопируй текст и вставь его в новое письмо. Фото и другие доказательства приложи в почте. Очень длинные письма могут передаваться не полностью — перед отправкой проверь черновик.",
      "The page works without a network connection. Templates, your name, and your language preference are saved only in this browser, if storage is allowed.": "Страница работает без подключения к сети. Шаблоны и имя сохраняются только в этом браузере, если он разрешает сохранение.",
      "Flex Claimer · independent tool": "Flex Claimer · независимый инструмент",
      "Not affiliated with Amazon. Add attachments in your mail app.": "Не связан с Amazon. Вложения добавляются в почтовом приложении.",
      "For cases where you arrived within the permitted check-in window but the app showed Late Scan. Check this statement in the email.": "Для случая, когда ты прибыл в разрешённое окно регистрации, но приложение показало Late Scan. Проверь эту формулировку в письме.",
      "Explain which standing entry is incorrect and why. Attach any evidence in your mail app.": "Опиши, какая запись в standing неверна и почему. Добавь имеющиеся доказательства в почтовом приложении.",
      "Include the package count, route distance, and when you ended the block in the app. Use this template when the workload could not be completed within the block time.": "Укажи количество посылок, расстояние и время завершения в приложении. Используй этот шаблон, если объём маршрута не позволил закончить доставку за время блока.",
      "For incorrect late marks when every package was delivered on time. Include the deadlines and delivery times; attach supporting evidence in your mail app.": "Для ошибочных отметок об опоздании, когда все посылки доставлены вовремя. Укажи сроки и время доставки; приложи подтверждения в почте.",
      "For packages undelivered because there was no access after 8 PM and customer calls were not permitted. Describe the delivery attempt.": "Для недоставленных посылок из-за отсутствия доступа после 20:00, когда звонить клиенту было нельзя. Укажи обстоятельства попытки доставки.",
      "For a damaged package returned to the station. Include the return date and attach the photo you took in your mail app.": "Для повреждённой посылки, возвращённой на склад. Укажи дату возврата и приложи сделанное фото в почтовом приложении.",
      "For undelivered-package entries that have remained in your standing for more than two months. Include the issue date and any previous support requests.": "Для недоставленных посылок, которые остаются в standing больше двух месяцев. Укажи дату записи и предыдущие обращения, если они были.",
      "For a review of late marks where the delay was no more than 5 minutes. Include the actual delay and its reasons.": "Для пересмотра отметок при задержке не более 5 минут. Укажи фактическую задержку и её причины.",
      "For a completed block with missing payment. Include the agreed amount in the details if needed.": "Для завершённого блока, за который не появилась оплата. При необходимости укажи согласованную сумму в уточнениях.",
      "Include your actual finish time, package count, and reasons for the delay in the details.": "Укажи фактическое время завершения, количество посылок и причины задержки в уточнениях.",
      "Open “Edit template” and enter your text. Variables in double braces will be replaced with your block details.": "Открой «Изменить шаблон» и введи свой текст. Переменные в двойных фигурных скобках заменятся данными блока.",
      "Replace your manual email edits with the template text?": "Заменить твои правки в письме текстом из шаблона?",
      "Template saved in this browser.": "Шаблон сохранён в этом браузере.",
      "Template applied. Browser storage is unavailable, so it may be lost after closing the page.": "Шаблон применён. Браузер не разрешил сохранение: после закрытия страницы он может потеряться.",
      "Enter a template subject and body.": "Заполни тему и текст шаблона.",
      "Unknown variable: ": "Неизвестная переменная: ",
      "Template error: ": "Ошибка в шаблоне: ",
      "Restore the default template for this issue type?": "Вернуть исходный шаблон для выбранного типа?",
      "The details have changed. Select “Update from template”, then review the email.": "Данные изменились. Нажми «Обновить из шаблона», затем проверь письмо.",
      "Enter an email subject and body.": "Заполни тему и текст письма.",
      "The email still contains template variables. Replace them with actual values.": "В письме остались переменные шаблона. Замени их значениями.",
      "Select an email recipient.": "Выбери получателя письма.",
      "Enter a valid email address for each selected recipient.": "Введи корректный email для каждого выбранного адреса.",
      "Enter the block date, then select “Create email”.": "Укажи дату блока, затем нажми «Создать email».",
      "Your mail app was requested to open. If no draft appeared, use Copy text.": "Запрошено открытие почты. Если черновик не появился, воспользуйся копированием.",
      "The text is selected. Copy it using the menu or Ctrl/Cmd+C.": "Текст выделен. Скопируй его через меню или Ctrl/Cmd+C.",
      "Email body copied.": "Текст письма скопирован."
    }
  },
  "templates": {
    "late": {
      "label": "Late Scan — unable to start a block",
      "hint": "For cases where you arrived within the permitted check-in window but the app showed Late Scan. Check this statement in the email.",
      "subject": "Unable to check in — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am writing about my scheduled block on {{block}}.\n\nI arrived within the permitted check-in window, but the app displayed “Late Scan” and prevented me from completing check-in and starting the block.\n\nPlease review the check-in records and the app error for this block. I request that any incorrect missed-block entry be removed and that my standing be corrected if it was affected. Please also review whether payment is due for this block.\n\nPlease confirm the outcome of your review."
    },
    "standing": {
      "label": "Incorrect standing issue",
      "hint": "Explain which standing entry is incorrect and why. Attach any evidence in your mail app.",
      "subject": "Request to review standing — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am requesting a review of a standing issue associated with my block on {{block}}.\n\nI believe the issue attributed to this block is incorrect. Please review the relevant delivery records, app activity, and any available support records together with the information provided in this email.\n\nIf the issue was recorded in error, please remove it from my delivery history and correct my standing. Please explain the outcome of the review and identify the specific issue if you determine that it should remain."
    },
    "undelivered": {
      "label": "Undelivered packages — route exceeded the block",
      "hint": "Include the package count, route distance, and when you ended the block in the app. Use this template when the workload could not be completed within the block time.",
      "subject": "Remove undelivered-package standing entries — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am requesting the removal of undelivered-package entries from my standing for my block on {{block}}.\n\nThe assigned route contained too many packages and required too much travel for the scheduled block duration. I was unable to deliver all of the assigned packages within that time. After the scheduled block time ended, I ended the block in the app.\n\nI do not consent to unpaid work beyond my scheduled block. I should not be penalized for refusing to work additional time without compensation when the assigned workload exceeds the paid block duration.\n\nPlease review the assigned package count, route distance, delivery timestamps, and the time I ended the block in the app. Remove the undelivered-package entries resulting from this excessive workload from my delivery history and correct my standing.\n\nPlease confirm that these entries have been removed and my standing has been corrected."
    },
    "noAccess": {
      "label": "Undelivered packages — no access after 8 PM",
      "hint": "For packages undelivered because there was no access after 8 PM and customer calls were not permitted. Describe the delivery attempt.",
      "subject": "Remove undelivered-package entries — no access — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am requesting the removal of undelivered-package entries from my standing for my block on {{block}}.\n\nI could not complete these deliveries for a valid reason: there was no access to the building or delivery location. The delivery attempts took place after 8:00 PM, when I was not permitted to call the customers to obtain access.\n\nThese packages were not left undelivered because I refused to deliver them. The access restrictions and the restriction on contacting customers prevented me from completing the deliveries.\n\nPlease review the delivery attempts and the circumstances described in this email. Remove these undelivered-package entries from my delivery history and correct my standing, as the deliveries could not be completed for reasons outside my control.\n\nPlease confirm that the entries have been removed and my standing has been corrected."
    },
    "damaged": {
      "label": "Damaged package — returned to the station",
      "hint": "For a damaged package returned to the station. Include the return date and attach the photo you took in your mail app.",
      "subject": "Remove undelivered-package entry — damaged package returned — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am disputing an undelivered-package entry affecting my standing for my block on {{block}}.\n\nThe package was damaged, so I did not deliver it to the customer. I returned it to the station and took a photo documenting the damage.\n\nPlease review the package return records and the photographic evidence. This was a damaged package returned to the station, not an unjustified failure to deliver.\n\nRemove the undelivered-package entry from my delivery history and correct my standing. Please confirm the outcome of your review."
    },
    "oldIssues": {
      "label": "Undelivered packages — entries older than 2 months",
      "hint": "For undelivered-package entries that have remained in your standing for more than two months. Include the issue date and any previous support requests.",
      "subject": "Remove undelivered-package entries older than two months — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am requesting a review and removal of undelivered-package entries associated with my block on {{block}}.\n\nThese entries have remained in my standing for more than two months and are still affecting it. I should not have to carry the impact of these historical entries indefinitely.\n\nPlease review why these entries remain active and remove them from my standing. If you decide that they must remain, explain how long they are expected to affect my standing, what determines their removal, and why they are still affecting it after more than two months.\n\nPlease provide a specific response about these entries and confirm any correction to my standing."
    },
    "onTime": {
      "label": "Delivered on time — incorrect late marks",
      "hint": "For incorrect late marks when every package was delivered on time. Include the deadlines and delivery times; attach supporting evidence in your mail app.",
      "subject": "Remove incorrect late-delivery standing entries — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am disputing late-delivery entries in my standing for my block on {{block}}.\n\nAll packages were delivered on time, within their applicable delivery deadlines. The entries marking these deliveries as late are incorrect.\n\nPlease compare the recorded delivery timestamps with the delivery deadlines shown for the packages. Remove the incorrect late-delivery entries from my delivery history and correct my standing.\n\nIf you believe any delivery was late, please identify the relevant delivery deadline and recorded delivery time so that I can understand and respond to the discrepancy.\n\nPlease confirm the outcome of your review and the correction to my standing."
    },
    "minorLate": {
      "label": "Late delivery — no more than 5 minutes",
      "hint": "For a review of late marks where the delay was no more than 5 minutes. Include the actual delay and its reasons.",
      "subject": "Review and remove minor late-delivery entries — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am requesting a review of late-delivery entries affecting my standing for my block on {{block}}.\n\nThe deliveries recorded as late had only a minor delay of no more than five minutes. I request that you consider the very short duration of the delay and remove these late-delivery entries from my delivery history.\n\nPlease review the applicable delivery deadlines, recorded delivery timestamps, and any circumstances described below. Given the minimal delay, I ask that these entries be removed and my standing corrected.\n\nPlease confirm the outcome of your review."
    },
    "payment": {
      "label": "Missing block payment",
      "hint": "For a completed block with missing payment. Include the agreed amount in the details if needed.",
      "subject": "Missing block payment — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am writing about missing payment for my block on {{block}}.\n\nI completed this block, but the corresponding payment is not reflected in my earnings.\n\nPlease review the block records and payment status, and process any outstanding payment owed. Please confirm the amount and the expected payment date, or explain why the payment has not been issued."
    },
    "overtime": {
      "label": "Route exceeded the block time",
      "hint": "Include your actual finish time, package count, and reasons for the delay in the details.",
      "subject": "Review of additional delivery time — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am writing about my block on {{block}}.\n\nThe assigned route took longer than the scheduled block time. Please review the assigned workload, route, delivery timestamps, and the circumstances described in this email.\n\nI request a review of the additional time worked and whether an earnings adjustment is due. If my standing was affected by an issue arising from this route, please review that issue as well.\n\nPlease confirm the outcome of your review."
    },
    "custom": {
      "label": "Custom template",
      "hint": "Open “Edit template” and enter your text. Variables in double braces will be replaced with your block details.",
      "subject": "Block review request — {{date}}, {{start}}",
      "body": "Hello Amazon Flex Support,\n\nI am writing about my block on {{block}}.\n\nPlease review the issue described below and let me know the outcome."
    }
  }
};
